spring.application.name=sb-ecom
server.port=8081

# H2 Console Settings
spring.h2.console.enabled=true

# H2 Fixed Database Configuration
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Image upload path
project.image=images/

# JPA / Hibernate settings
spring.jpa.show-sql=true