spring.application.name=sb-ecom
server.port=8081
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:b11fc6d7-c246-4063-b2d6-667fb7d9948d

project.image=images/
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=create-drop
